baseURL = "https://lixeek.com/"
languageCode = "en-us"
title = "Lixeek's Blog"

[taxonomies]
  tag = "tags"
  category = "categories"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Posts"
  url = "/posts/"
  weight = 2

[[menu.main]]
  name = "Art"
  url = "/categories/art/"
  weight = 3

[[menu.main]]
  name = "Photos"
  url = "/categories/photos/"
  weight = 4

[[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 5

[params]
  description = "Art, videos, and updates by Lixeek"
  author = "Lixeek"

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]

paginate = 12

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
